### PR TITLE
[client] Fluss client shouldn't load plugin by thread context classloader.

### LINKED ISSUE #1262: Fluss client shouldn't load plugin by thread contextclassloader.
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.7.0 (latest release)

### Please describe the bug 🐞

Currently, when we put fluss connector into flink lib, the job preforms well. When I run with "--jar" or "add jar", the sql-client will fail with :
```java
ERROR] Could not execute SQL statement. Reason:
com.alibaba.fluss.metadata.ValidationException: No plugin for the protocol 'sasl' is found in the classpath
```

It's because when sql gateway run(in flink 1.20), the thread classloader is not the user classloader. Thus, though user classloader can loaded flink-fluss-1.20.jar, but the thread classloader cannot do it.

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #1262

### CODE REVIEW

**Comment by loserwang1024** [comment]
@wuchong @leonardBang , CC

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java [hunk 1]
```diff
@@ -657,6 +660,28 @@ void testAuthentication() throws Exception {
         }
     }
 
+    // this test is to mock `--jar` which is not loaded by the app classloader.
+    @Test
+    void testNotIncludedInThreadContextClassloader() throws Exception {
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java]: Move to `FlinkAuthorizationITCase`, and refactored into assert the success of catalog registration.

Comment (loserwang1024) [reply fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java]: modifed it.
