### PR TITLE
[lake/paimon] Support tiering paimon deletion vector enabled table

### LINKED ISSUE #1668: Introduce IcebergRecordAsFlussRow
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Description

Introduce IcebergRecordAsFlussRow

### Willingness to contribute

- [x] I'm willing to submit a PR!

### LINKED ISSUE #1688: Tiering service should support paimon deletion-vector table
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Description

Currently, it'll throw exception:

Image

### Willingness to contribute

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #1688

### CODE REVIEW

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java [hunk 1]
```diff
@@ -55,8 +60,20 @@ public MergeTreeWriter(
     }
 
     private static TableWriteImpl<KeyValue> createTableWrite(FileStoreTable fileStoreTable) {
+        // we allow users to configure the temporary directory used by fluss tiering
+        // since the default java.io.tmpdir may not be suitable.
+        // currently, we don't expose the option, as a workaround way, maybe in the future we can
+        // expose it if it's needed
+        Map<String, String> props = fileStoreTable.options();
+        String tmpDir = props.get(FLUSS_TIERING_TMP_DIR_KEY);
+        if (tmpDir == null) {
```
Comment (beryllw) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java]: May be we could use `getOrDefault`.
```
 String tmpDir = props.getOrDefault(FLUSS_TIERING_TMP_DIR_KEY, System.getProperty("java.io.tmpdir"));
```

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java [hunk 2]
```diff
@@ -55,8 +60,20 @@ public MergeTreeWriter(
     }
 
     private static TableWriteImpl<KeyValue> createTableWrite(FileStoreTable fileStoreTable) {
+        // we allow users to configure the temporary directory used by fluss tiering
+        // since the default java.io.tmpdir may not be suitable.
+        // currently, we don't expose the option, as a workaround way, maybe in the future we can
+        // expose it if it's needed
```
Comment (beryllw) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java:66]: May be we could use Flink conf `io.tmp.dirs`.

**Comment by beryllw** [comment]
LGTM!

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java (hunk 2 above)
Comment (luoyuxia) [reply fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java:66]: I'd like to express it as used by fluss tiering explicitly in case of mixing other engines usage. Just like option `client.scanner.io.tmpdir`.
