### PR TITLE
[lake] Ensure LakeStoragePlugin uses the plugin classloader for all operations

### LINKED ISSUE #1168: Use Paimon Hive Catalog with hiveconf configured will throw No FileSystem for scheme: file
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

If configure the following in `server.yaml`
```
datalake.format: paimon

datalake.paimon.metastore: hive
datalake.paimon.url: thrift://xxxx:9093
datalake.paimon.warehouse: hdfs://xxx/xxx
datalake.paimon.hadoop-conf-dir: file:///opt/hive-conf
datalake.paimon.hive-conf-dir: file:///opt/hive-conf
```
Then, start the coordinator, the following exception will be thrown:
```
Caused by: java.io.IOException: No FileSystem for scheme: file
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2799) ~[?:?]
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2810) ~[?:?]
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100) ~[?:?]
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2849) ~[?:?]
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2831) ~[?:?]
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389) ~[?:?]
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356) ~[?:?]
        at org.apache.paimon.hive.HiveCatalog.createHiveConf(HiveCatalog.java:1354) ~[?:?]
        at org.apache.paimon.hive.HiveCatalog.createHiveConf(HiveCatalog.java:1412) ~[?:?]
        at org.apache.paimon.hive.HiveCatalog.createHiveCatalog(HiveCatalog.java:1379) ~[?:?]
        at org.apache.paimon.hive.HiveCatalogFactory.create(HiveCatalogFactory.java:37) ~[?:?]
        at org.apache.paimon.catalog.CatalogFactory.createUnwrappedCatalog(CatalogFactory.java:84) ~[?:?]
        at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:71) ~[?:?]
        at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:67) ~[?:?]

```
We have put `flink-shaded-hadoop-2-uber-2.8.3-10.0.jar` in /plugins/paimon/ , which should include LocalFileSystem to support `file` scheme. 

The reason why the exception happens is that: 
org.apache.hadoop.fs.Path.getFileSystem will use thread current classloader(which is app classloader) to load filesystem, but obviously  it's not in  app classloader. If I also copy `flink-shaded-hadoop-2-uber-2.8.3-10.0.jar` into FLUSS_HOME/lib.
It will throw class not cast exception since hadoop classes in both `/plugins/paimon/` and `FLUSS_HOME/lib`.

#### work around
Now, I found a workround:
- Move /plugins/paimon/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar to `FLUSS_HOME/lib`
- Add a option in `server.yaml`:
```
plugin.classloader.parent-first-patterns.default: java.,com.alibaba.fluss.,javax.annotation.,org.slf4j,org.apache.log4j,org.apache.logging,org.apache.commons.logging,ch.qos.logback,org.apache.hadoop.
``` 

To solve this, while calling pluginable lake catalog, we may need to set the current thread classloader to the classloader of lake catalog(which is pluginClassloader including hadoop classes). 

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by beryllw**
### Purpose

Linked issue: close #1168

### Brief change log

Use plugin classloader as thread current classloader, and ensure LakeStoragePlugin uses the plugin classloader for all operations

### Tests

com.alibaba.fluss.lake.lakestorage.LakeStorageTest

### CODE REVIEW

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+import java.util.Collections;
+import java.util.HashMap;
+import java.util.Iterator;
+import java.util.Map;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.assertj.core.api.Assertions.assertThatThrownBy;
+
+/** Tests for the {@link LakeStorage} base class. */
+public class LakeStorageTest {
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]: nit:
```suggestion
class LakeStorageTest {
```

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+    private static final String TEST_LAKE_PLUGIN_FORMAT = "test-plugin";
+
+    @Test
+    void testInvalidPlugin(@TempDir Path tempDir) throws Exception {
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]: nit:
Parameter 'tempDir' is never used

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+        final Map<Class<?>, Iterator<?>> lakeStoragePlugins = new HashMap<>();
+        // use LocalFileSystem as the filesystem of schema 'testPluginSchema'
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]: nit: remove this comment.

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+                Collections.singletonList(new LakeStorageTest.TestPluginLakeStoragePlugin())
+                        .iterator());
+
+        assertThatThrownBy(
+                        () ->
+                                LakeStoragePluginSetUp.fromDataLakeFormat(
+                                        TEST_LAKE_PLUGIN_FORMAT + "1",
+                                        new TestingPluginManager(lakeStoragePlugins)))
+                .isInstanceOf(UnsupportedOperationException.class)
+                .hasMessageContaining("No LakeStoragePlugin can be found for datalake format: ");
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]:
```suggestion
               .hasMessage("No LakeStoragePlugin can be found for datalake format: test-plugin1");
```

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+    }
+
+    @Test
+    void testWithPluginManager(@TempDir Path tempDir) throws Exception {
+
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]: nit:
remove blank line.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java [hunk 6]
```diff
@@ -36,28 +33,26 @@
 public class LakeStoragePluginSetUp {
 
     @Nullable
-    public static LakeStoragePlugin fromConfiguration(
-            final Configuration configuration, @Nullable final PluginManager pluginManager) {
-        DataLakeFormat dataLakeFormat = configuration.get(ConfigOptions.DATALAKE_FORMAT);
+    public static LakeStoragePlugin fromDataLakeFormat(
+            final String dataLakeFormat, @Nullable final PluginManager pluginManager) {
         if (dataLakeFormat == null) {
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java]: Let's remove
```
if (dataLakeFormat == null) {
 return null;
}
```
And then in `CoordinatorServer`, not pass null to this method.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java [hunk 7]
```diff
@@ -36,28 +33,26 @@
 public class LakeStoragePluginSetUp {
 
     @Nullable
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java]: Also remove `@Nullable` annotation

File: fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java [hunk 8]
```diff
@@ -0,0 +1,146 @@
...
+                        () ->
+                                LakeStoragePluginSetUp.fromDataLakeFormat(
+                                        TEST_LAKE_PLUGIN_FORMAT + "1",
+                                        new TestingPluginManager(lakeStoragePlugins)))
+                .isInstanceOf(UnsupportedOperationException.class)
+                .hasMessageContaining("No LakeStoragePlugin can be found for datalake format: ");
+    }
+
+    @Test
+    void testWithPluginManager(@TempDir Path tempDir) throws Exception {
```
Comment (luoyuxia) [inline fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java]: nit:
Parameter 'tempDir' is never used

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java [hunk 9]
```diff
@@ -247,8 +248,10 @@ protected void startServices() throws Exception {
 
     @Nullable
     private LakeCatalog createLakeCatalog() {
+        DataLakeFormat dataLakeFormat = conf.get(ConfigOptions.DATALAKE_FORMAT);
         LakeStoragePlugin lakeStoragePlugin =
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java]: nit:
```
if (dataLakeFormat == null) {
return null
}
```

**Review by luoyuxia — COMMENTED** [review]
@beryllw Thanks for the PR. Only left minor comments. Otherwise, LGTM.
Besides, could you please verify this pr in your own env to make this pr fix the problem that the issue describes.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+import com.alibaba.fluss.metadata.TableDescriptor;
+import com.alibaba.fluss.metadata.TablePath;
+import com.alibaba.fluss.utils.TemporaryClassLoaderContext;
+import com.alibaba.fluss.utils.WrappingProxy;
+
+/**
+ * A wrapper around {@link LakeStoragePlugin} that ensures the plugin classloader is used for all
+ * {@link LakeCatalog} and {@link LakeStorage} operations.
+ */
+public class PluginLakeStorageWrapper implements LakeStoragePlugin {
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java:32]: Sorry for missing that. Can we wrap `LakeCatalog` instead of `LakeStoragePlugin`, only `LakeCatalog` will be called in server side. So, only `LakeCatalog` matters. Also, currently, it doesn't wrap the `LakeCatalog#catalogtable` method, which I think may need to set thread current context.

**Comment by beryllw** [comment]
> Could you please verify this pr in your own env to make this pr fix the problem that the issue describes.

Yes. I encountered an issue where plugin HDFS and Paimon can't use Kerberos authentication with the plugin class loader. We might need a PR to fix this. Additionally, shading `org.apache.commons` is necessary to prevent conflicts between Fluss and the Hadoop dependencies on the machine.

**Comment by beryllw** [comment]
> Plugin HDFS and Paimon can't use Kerberos authentication with the plugin class loader.

By setting  `plugin.classloader.parent-first-patterns.default=java.,com.alibaba.fluss.,javax.annotation.,org.slf4j,org.apache.log4j,org.apache.logging,org.apache.commons.logging,ch.qos.logback,hdfs-site,core-site,org.apache.hadoop.,META-INF`  to include the necessary patterns, the problem can be resolved.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+            }
+        }
+
+        @Override
+        public LakeCatalog getWrappedDelegate() {
+            return inner;
+        }
+    }
+
+    static class ClassLoaderFixingLakeStorage implements LakeStorage, WrappingProxy<LakeStorage> {
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java:93]: We don't need to wrap `LakeStorage` for simplicity since the server side will never used it currently.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java [hunk 12]
```diff
@@ -0,0 +1,122 @@
...
+import com.alibaba.fluss.exception.TableAlreadyExistException;
+import com.alibaba.fluss.lake.writer.LakeTieringFactory;
+import com.alibaba.fluss.metadata.TableDescriptor;
+import com.alibaba.fluss.metadata.TablePath;
+import com.alibaba.fluss.utils.TemporaryClassLoaderContext;
+import com.alibaba.fluss.utils.WrappingProxy;
+
+/**
+ * A wrapper around {@link LakeStoragePlugin} that ensures the plugin classloader is used for all
+ * {@link LakeCatalog} and {@link LakeStorage} operations.
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java]: nit
```suggestion
 * {@link LakeCatalog} operations.
```

**Review by luoyuxia — COMMENTED** [review]
@beryllw Thanks for update. Left minor comments. Otherwise, LGTM!

File: fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java (hunk 11 above)
Comment (beryllw) [reply fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java:93]: `LakeCatalog` is created by `LakeStorage`, which needs to provide the plugin class loader to `LakeCatalog` unless we eliminate the need for the `LakeStorage` interface. Am I misunderstanding something?

Comment (luoyuxia) [reply fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java:93]: Sorry for misleading. I'm intending to means:
Change 
```
@Override
        public LakeTieringFactory<?, ?> createLakeTieringFactory() {
            try (TemporaryClassLoaderContext ignored = TemporaryClassLoaderContext.of(loader)) {
                return inner.createLakeTieringFactory();
            }
        }
```
to 
```
public LakeTieringFactory<?, ?> createLakeTieringFactory() {
            return inner.createLakeTieringFactory();
        }
```
Not to wrap LakeTieringFactory.

**Review by luoyuxia — APPROVED** [review]
Thanks. LGTM!
