### PR TITLE
[flink] Fluss enumerator partition discovery in fixed delay rather than fixed rate.

### LINKED ISSUE #1632: Fluss enumerator partition discovery in fixed delay rather than fixed rate.
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.7.0 (latest release)

### Please describe the bug 🐞

Currently, enumerator partition discovery in  fixed rate. If the `listPartitions` and `initPartitionedSplits` cost more than 10s, the event will backlog. Then, a newly discovered split will be added and assigned after a long time.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #1632

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+                        context.callAsync(
+                                () -> {
+                                    throw t;
+                                },
+                                handler);
+                    }
+                },
+                initialDelay,
+                delay,
+                TimeUnit.MILLISECONDS);
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java]: We can wrap the `callable` with a `CompleteFuture` to blocking wait in the `Runnable` of `workerExecutor.scheduleWithFixedDelay`.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+ * {@link SplitEnumeratorContext} natively supports asynchronous calls with fixed delay scheduling.
+ *
+ * <p>This executor wraps a single-threaded {@link ScheduledExecutorService} to handle async
+ * operations and route their results back to the coordinator thread through the {@link
+ * SplitEnumeratorContext#callAsync} methods.
+ */
+@Internal
+public class WorkerExecutor {
+    protected final SplitEnumeratorContext<SourceSplitBase> context;
+    private final ScheduledExecutorService workerExecutor;
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java]: Use another variable name like `scheduledExecutor` to avoid naming conflict with the class name.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java [hunk 3]
```diff
@@ -85,11 +86,14 @@
  *       will be assigned to same reader.
  * </ul>
  */
+@Internal
 public class FlinkSourceEnumerator
         implements SplitEnumerator<SourceSplitBase, SourceEnumeratorState> {
+    // TODO: remove it until SplitEnumeratorContext.callAsync supports fixed delay.
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java]: move this comment with the `workerExecutor`. Besides, you can add the FLIP or JIRA id if there is already one.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+import java.util.concurrent.Callable;
+import java.util.concurrent.Executors;
+import java.util.concurrent.ScheduledExecutorService;
+import java.util.concurrent.TimeUnit;
+import java.util.function.BiConsumer;
+
+/**
+ * A worker executor that is used to schedule asynchronous tasks to extend {@link
+ * SplitEnumeratorContext} with fixed delay capabilities. This class serves as a workaround until
+ * {@link SplitEnumeratorContext} natively supports asynchronous calls with fixed delay scheduling.
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java]: please explain why we can't use `SplitEnumeratorContext#callAsync(java.util.concurrent.Callable<T>, java.util.function.BiConsumer<T,java.lang.Throwable>, long, long)`

**Review by wuchong — APPROVED** [review]
