### PR TITLE
[flink] Improve TableAlreadyExistException message for LakeCatalog.createTable()

### LINKED ISSUE #1637: Improve TableAlreadyExistException message for LakeCatalog.createTable()
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Description

When user create table in fluss catalog with paimon lakehouse twice. Current error message:
```
Table (or view) xxxxxx already exists in Catalog xxxxx.
```
The message doesn't clearly indicate the failure occurred in LakeCatalog.createTable().
We could update it to explicitly state that table creation failed via LakeCatalog.createTable().

### Willingness to contribute

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by beryllw**
### Purpose

Linked issue: close #1637

### Brief change log

Add `LakeTableAlreadyExistException` to  to identify lake catalog table already exist Exception.

### CODE REVIEW

**Comment by beryllw** [comment]
Likely not related to this PR.
```
Error:  Failures: 
Error:    CoordinatorEventProcessorTest.lambda$retryVerifyContext$46:1097->lambda$preparePartitionAssignment$28:856 
```

File: fluss-rpc/src/main/java/org/apache/fluss/rpc/protocol/Errors.java [hunk 1]
```diff
@@ -214,7 +215,9 @@ public enum Errors {
     INVALID_SERVER_RACK_INFO_EXCEPTION(
             52, "The server rack info is invalid.", InvalidServerRackInfoException::new),
     LAKE_SNAPSHOT_NOT_EXIST(
-            53, "The lake snapshot is not exist.", LakeTableSnapshotNotExistException::new);
+            53, "The lake snapshot is not exist.", LakeTableSnapshotNotExistException::new),
+    LAKE_TABLE_ALREADY_EXIST(
+            54, "The lake table is already exist.", LakeTableAlreadyExistException::new);
```
Comment (luoyuxia) [inline fluss-rpc/src/main/java/org/apache/fluss/rpc/protocol/Errors.java]:
```suggestion
            54, "The lake table already exists.", LakeTableAlreadyExistException::new);
```

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkCatalog.java [hunk 2]
```diff
@@ -380,6 +380,8 @@ public void createTable(ObjectPath objectPath, CatalogBaseTable table, boolean i
                 throw new DatabaseNotExistException(getName(), objectPath.getDatabaseName());
             } else if (CatalogExceptionUtils.isTableAlreadyExist(t)) {
                 throw new TableAlreadyExistException(getName(), objectPath);
+            } else if (CatalogExceptionUtils.isLakeTableAlreadyExist(t)) {
+                throw new TableAlreadyExistException("lakeCatalog", objectPath, t);
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkCatalog.java]: I'm wondering can we use `CatalogException` to show the detail error message of 
```
The table xx already exists in xx catalog, please "
                                        + "first drop the table in xx catalog or use a new table name
```
since it's more clear to me

File: fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/catalog/LakeEnabledFlinkCatalogTest.java [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+                CatalogTable.of(
+                        Schema.newBuilder().fromResolvedSchema(resolvedSchema).build(),
+                        "test comment",
+                        Collections.emptyList(),
+                        options);
+        return new ResolvedCatalogTable(origin, resolvedSchema);
+    }
+
+    @Test
+    void testCreateLakeTable() throws Exception {
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/catalog/LakeEnabledFlinkCatalogTest.java]: Can we move the test case to `FlinkCatalogTest`? We can enable datalake for the FlussCluster used in `FlinkCatalogTest`

File: fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/utils/CatalogTableTestUtils.java [hunk 4]
```diff
@@ -80,6 +81,8 @@ private static void assertOptionsEqual(
             Map<String, String> actualOptions, Map<String, String> expectedOptions) {
         actualOptions.remove(BOOTSTRAP_SERVERS.key());
         actualOptions.remove(TABLE_REPLICATION_FACTOR.key());
+        // TODO:remove this after #1646
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/utils/CatalogTableTestUtils.java]: Do we still need this todo considering https://github.com/apache/fluss/issues/1646#issuecomment-3256810003
?

**Comment by luoyuxia** [comment]
@beryllw Test fail

**Review by luoyuxia — APPROVED** [review]
+1
