### PR TITLE
[kv] coordinator must handle inconsistency or broken snapshot scenarios

### LINKED ISSUE #1469: [KV] Coordinator Permanently Rejects KV Snapshot Commit Upon Encountering Corrupted History KV Snapshot
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.7.0 (latest release)

### Please describe the bug 🐞

Current Situation: The bug described in issue https://github.com/apache/fluss/issues/1304 may cause inconsistent snapshot metadata between remote storage and ZooKeeper. This inconsistency prevents the affected table buckets from committing new KV snapshots.

### Solution

The Coordinator must handle inconsistency or broken snapshot scenarios.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by platinumhamburg**
### Purpose

Linked issue: close #1469

### CODE REVIEW

**Comment by rafaelsmf** [comment]
Thanks for the fixing! I was testing Fluss locally and after the zookeeper container restart, I faced the issue related to this PR.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java [hunk 1]
```diff
@@ -120,13 +121,46 @@ private CompletedSnapshotStore createCompletedSnapshotStore(
...
 
         for (CompletedSnapshotHandle snapshotStateHandle : initialSnapshots) {
-            retrievedSnapshots.add(checkNotNull(snapshotStateHandle.retrieveCompleteSnapshot()));
+            try {
+                retrievedSnapshots.add(
+                        checkNotNull(snapshotStateHandle.retrieveCompleteSnapshot()));
+            } catch (Exception e) {
+                if (e.getMessage().contains(SNAPSHOT_META_DATA_NOT_EXISTS_ERROR_MESSAGE)) {
+                    LOG.error(
+                            "metadata not found for snapshot {} of table bucket {}, maybe snapshot already removed or broken, detail errorMsg: {}",
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java]: minor: Let's capitalize the first letter of log messages to maintain consistency with the project's logging style.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java [hunk 2]
```diff
@@ -120,13 +121,46 @@ private CompletedSnapshotStore createCompletedSnapshotStore(
...
+                            snapshotStateHandle.getSnapshotId(),
+                            tableBucket,
+                            e.getMessage());
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java]: Could we also print the full exception stack trace? I'm concerned that the root cause might be hidden within nested exceptions.

```suggestion
                            e.getMessage(), 
                            e);
```

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/CompletedSnapshotHandle.java [hunk 3]
```diff
@@ -40,11 +40,13 @@
  */
 public class CompletedSnapshotHandle {
 
+    private long snapshotId;
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/CompletedSnapshotHandle.java]: use `final` modifier to mark this field is immutable.

**Review by wuchong — COMMENTED** [review]
Could you add a test to reproduce this problem and verify the bug is fixed? Maybe a unit test in `CompletedSnapshotStoreManagerTest`.

**Comment by wuchong** [comment]
I saw you mentioned the https://github.com/apache/fluss/issues/1304 in the issue description, can this pull request fix the problem of #1304?

**Comment by platinumhamburg** [comment]
> I saw you mentioned the #1304 in the issue description, can this pull request fix the problem of #1304?

This PR cannot be used to close issue #1304 at this time. Issue #1304 may introduce broken snapshots or inconsistent snapshot metadata, while this PR can only handle already existing inconsistencies. I will submit another PR to fix #1304 later.

**Comment by platinumhamburg** [comment]
> Could you add a test to reproduce this problem and verify the bug is fixed? Maybe a unit test in `CompletedSnapshotStoreManagerTest`.

Thank you for your feedback. I have addressed all of your suggestions and supplemented the test cases to ensure correctness.

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java [hunk 4]
```diff
@@ -172,6 +181,50 @@ void testRemoveCompletedSnapshotStoreFromManager() throws Exception {
...
+        when(validSnapshotHandle.getMetadataFilePath())
+                .thenReturn(validSnapshot.getMetadataFilePath());
+        when(validSnapshotHandle.retrieveCompleteSnapshot()).thenReturn(validSnapshot);
+
+        CompletedSnapshot invalidSnapshot =
+                KvTestUtils.mockCompletedSnapshot(tempDir, tableBucket, 2L);
+        CompletedSnapshotHandle invalidSnapshotHandle = mock(CompletedSnapshotHandle.class);
+        when(invalidSnapshotHandle.getSnapshotId()).thenReturn(invalidSnapshot.getSnapshotID());
+        when(invalidSnapshotHandle.getMetadataFilePath())
+                .thenReturn(invalidSnapshot.getMetadataFilePath());
```
Comment (wuchong) [inline fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java]: Please avoid use Mockito, use reusable test implementations instead. (see [the code quality guide and reason here](https://flink.apache.org/how-to-contribute/code-style-and-quality-common/#avoid-mockito---use-reusable-test-implementations)). 

Here, we can easily construct the valid and invalid `CompletedSnapshotHandle` using its constructor, one has valid path and the other has invlid path. This makes the code easy to maintain for the future, and cover more code path.

**Review by wuchong — COMMENTED** [review]
Thanks @platinumhamburg for the fixing. 

Just a quick note: could you please avoid squashing commits while responding to review comments? Keeping the changes in separate commits makes it much easier to track what has been updated since the last review.

When commits are squashed, it becomes difficult to distinguish new changes from previous ones, forcing reviewers to review the entire changes again. This significantly increases review time and may slow down the overall merge process.

The committer will help to squash commits and improve the commit message before merging the PR. So don’t worry about having multiple "fix" commits in PR.

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java (hunk 4 above)
Comment (platinumhamburg) [reply fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java]: Thanks for the suggestion. I've refactored this case to avoid using Mockito.

**Review by wuchong — APPROVED** [review]
