### PR TITLE
[kv] Fix non-target columns not being nulled during partial update on first insert

### LINKED ISSUE #2843: Invalid partial update for PK table
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.9.0 (latest release)

### Please describe the bug 🐞

According to the doc of https://fluss.apache.org/docs/next/apis/java-client/#partial-updates , I found the un-specified columns will also be updated. 

```java
class User {
    public String id;
    public Integer age;
    public LocalDateTime createdAt;
    public boolean active;

    public User(String id, Integer age, LocalDateTime createdAt, boolean active) {
        this.id = id;
        this.age = age;
        this.active = active;
        this.createdAt = createdAt;
    }

    public String getId() {
        return id;
    }

    public Integer getAge() {
        return age;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public boolean isActive() {
        return active;
    }

    @Override
    public String toString() {
        return "User{"
                + "id='"
                + id
                + '\''
                + ", age="
                + age
                + ", createdAt="
                + createdAt
                + ", active="
                + active
                + '}';
    }

    public static User from(InternalRow row) {
        String id = row.getString(0).toString();
        Integer age = row.getInt(1);
        LocalDateTime createdAt = row.getTimestampNtz(2, 1).toLocalDateTime();
        boolean active = row.getBoolean(3);
        return new User(id, age, createdAt, active);
    }

    public static GenericRow to(User user) {
        GenericRow row = new GenericRow(4);
        row.setField(0, BinaryString.fromString(user.getId()));
        row.setField(1, user.getAge());
        row.setField(2, TimestampNtz.fromLocalDateTime(user.getCreatedAt()));
        row.setField(3, user.isActive());
        return row;
    }



Admin admin = conn.getAdmin();

        Schema schema =
                Schema.newBuilder()
                        .column("id", DataTypes.STRING())
                        .column("age", DataTypes.INT())
                        .column("created_at", DataTypes.TIMESTAMP())
                        .column("is_active", DataTypes.BOOLEAN())
                        .primaryKey("id")
                        .build();
        TableDescriptor tableDescriptor =
                TableDescriptor.builder()
                        .schema(schema)
                        .build();

        TablePath tablePath = TablePath.of("fluss", "fluss_toolkit_partial_update_t1");
        admin.createTable(tablePath, tableDescriptor, true).get();

        Table table = conn.getTable(tablePath);

        User user = new User("1", 20, LocalDateTime.now(), false);
        GenericRow row = User.to(user);
        System.out.println("Upserting rows to the table");
        UpsertWriter writer = table.newUpsert().partialUpdate("id", "age").createWriter();
        writer.upsert(row);
        writer.flush();

        GenericRow rowKey = new GenericRow(1);
        rowKey.setField(0, BinaryString.fromString("1"));
        LookupResult lookup = table.newLookup().createLookuper().lookup(rowKey).get();
        lookup.getRowList().forEach(x -> System.out.println(User.from(x)));

        // 4. delete the table
        admin.dropTable(tablePath, true).get();
```

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by binary-signal**
### Purpose

Linked issue: close #2843

This pull request fixes a bug where `partialUpdate` on a Primary Key table during a first insert (where no row exists for that key) incorrectly stored all columns. This resulted in non-target columns retaining their values from the client row instead of being properly set to null.

### Brief change log

The root cause was isolated to `KvTablet.processUpsert()`, which bypassed the `RowMerger` when `oldValueBytes == null` (indicating a first insert) and passed the raw row directly to `applyInsert()`. As a result, `PartialUpdater.updateRow(null, partialValue)` was never invoked.

The following changes were implemented to resolve this:
* **`fluss-server/.../rowmerger/RowMerger.java`:** Added a default `mergeInsert(BinaryValue newValue)` method that returns `newValue` unchanged. This ensures safety and backward compatibility for all existing mergers.
* **`fluss-server/.../rowmerger/DefaultRowMerger.java`:** Overrode `mergeInsert` within the inner `PartialUpdateRowMerger` class to call `partialUpdater.updateRow(null, newValue)`. This guarantees non-target columns are nulled out on the first insert.
* **`fluss-server/.../kv/KvTablet.java`:** Updated `processUpsert()` to execute `currentMerger.mergeInsert(currentValue)` prior to `applyInsert()`. This ensures partial updates are accurately applied throughout the initial insert process.

### Tests

Added two new unit tests to `fluss-server/.../kv/KvTabletTest.java`:
* `testPartialUpdateFirstInsertNullsNonTargetColumns`: Verifies that non-target columns are set to null on a first insert, even if the client row contains values for them.
* `testPartialUpdateFirstInsertThenUpdate`: Verifies the full lifecycle by ensuring that an initial insert with a partial update nulls non-target columns, and a subsequent partial update correctly retains the previously stored values.

### API and Format

No. This is an internal data processing logic fix. No public APIs or storage formats are modified.

### Documentation

No. This is a bug fix correcting existing behavior. No documentation updates are required.

### CODE REVIEW

**Comment by fresh-borzoni** [comment]
@binary-signal 
Ty for the PR, I recently landed #2594 in the same code area, so you need to rebase and adapt your PR to the changes introduced

I will help to review it then

**Comment by binary-signal** [comment]
> @binary-signal 
> 
> Ty for the PR, I recently landed #2594 in the same code area, so you need to rebase and adapt your PR to the changes introduced
> 
> 
> 
> I will help to review it then

Thanks for the heads, I am rebasing

**Comment by binary-signal** [comment]
@fresh-borzoni it's rebased, no git conflicts. I will let the CI run and then have a look  if any further changes are needed

**Comment by binary-signal** [comment]
@fresh-borzonit  rebase and adapt your PR, I've rebased latest changes from main

**Review by fresh-borzoni — COMMENTED** [review]
@binary-signal Ty for the PR, overall your approach works, but `mergeInsert` is unnecessary as PartialUpdater.updateRow(null, v) already handles null oldValue, so you can just call currentMerger.merge(null, currentValue) in the insert path. This way - no interface change needed.

But it requires checking other mergers if they handle null gracefully, do you mind to check?

**Comment by luoyuxia** [comment]
@binary-signal Hi, thanks for the pr, do you still have time to update the pr according to the comment?

**Comment by binary-signal** [comment]
@fresh-borzoni and @luoyuxia it took a bit more time than expected but here's my findings


There are 6 `*RowMerger` classes , 4 out of 6 (`DefaultRowMerger`, `PartialRowMerger`, `AggregateRowMerger` and `PartialAggregateRowMerger` can handle `null`, no change needed there. But this leaves 2 mergers `FirtRowRowMerger` and `VersionedRowMerger` that need fixing. More specifically

- FirsRowRowMerger: Returns oldValue directly — would return null on first insert instead of newValue

- VersionedRowMerger: Calls oldValue.row without null check — NPE on first insert

**Comment by binary-signal** [comment]
comment addressed in latest commit.

**Comment by luoyuxia** [comment]
@fresh-borzoni Hi, do you want to have another look?

File: fluss-server/src/test/java/org/apache/fluss/server/kv/KvTabletTest.java [hunk 1]
```diff
@@ -463,6 +463,85 @@ void testPartialUpdateAndDelete() throws Exception {
         checkEqual(actualLogRecords, expectedLogs, rowType);
     }
 
+    @Test
+    void testPartialUpdateFirstInsertNullsNonTargetColumns() throws Exception {
```
Comment (luoyuxia) [inline fluss-server/src/test/java/org/apache/fluss/server/kv/KvTabletTest.java]: Could this method be removed since seems testPartialUpdateFirstInsertThenUpdate has similar verify logic

**Review by luoyuxia — COMMENTED** [review]
@binary-signal Thanks for the pr. Left minor commets

File: fluss-server/src/test/java/org/apache/fluss/server/kv/KvTabletTest.java (hunk 1 above)
Comment (binary-signal) [reply fluss-server/src/test/java/org/apache/fluss/server/kv/KvTabletTest.java]: Thank you for the review, good catch. Comment Addressed

**Review by fresh-borzoni — APPROVED** [review]
@binary-signal TY, LGTM 👍 

nit: the new `oldValue == null` guards in FirstRowRowMerger and VersionedRowMerger have no direct test. We might wish to add them, just to prevent regression if someone decides to do refactoring in this area

**Comment by binary-signal** [comment]
@fresh-borzoni I will add tests for that case too, thanks xD

**Comment by binary-signal** [comment]
addressed  comments

**Review by luoyuxia — APPROVED** [review]
+1
