### PR TITLE
Fluss Flink Lookup function return null rather than PartitionNotException if paritition not exists.

### LINKED ISSUE #1317: Fluss Flink Lookup function return null rather than PartitionNotExistException if cannot match paritition.
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.7.0 (latest release)

### Please describe the bug 🐞

Currenly,  when we use dim table, if partition is not found ,will thrown exception.
```java
com.alibaba.fluss.exception.FlussRuntimeException: Failed to update metadata
	at com.alibaba.fluss.client.metadata.MetadataUpdater.updateMetadata(MetadataUpdater.java:270)
	at com.alibaba.fluss.client.metadata.MetadataUpdater.checkAndUpdatePartitionMetadata(MetadataUpdater.java:192)
	at com.alibaba.fluss.client.utils.ClientUtils.getPartitionId(ClientUtils.java:131)
	at com.alibaba.fluss.client.lookup.PrimaryKeyLookuper.lookup(PrimaryKeyLookuper.java:113)
	at com.alibaba.fluss.flink.source.lookup.FlinkAsyncLookupFunction.fetchResult(FlinkAsyncLookupFunction.java:143)
	at com.alibaba.fluss.flink.source.lookup.FlinkAsyncLookupFunction.asyncLookup(FlinkAsyncLookupFunction.java:126)
	at org.apache.flink.table.functions.AsyncLookupFunction.eval(AsyncLookupFunction.java:52)
	at LookupFunction$1083.asyncInvoke(Unknown Source)
	at org.apache.flink.table.runtime.operators.join.lookup.AsyncLookupJoinRunner.asyncInvoke(AsyncLookupJoinRunner.java:121)
	at org.apache.flink.table.runtime.operators.join.lookup.AsyncLookupJoinRunner.asyncInvoke(AsyncLookupJoinRunner.java:44)
	at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator.processElement(AsyncWaitOperator.java:273)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:245)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:217)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:169)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:68)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:617)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop
```

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #1317

### CODE REVIEW

**Comment by loserwang1024** [comment]
@wuchong @luoyuxia , CC

File: fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java [hunk 1]
```diff
@@ -150,9 +151,18 @@ public CompletableFuture<LookupResult> lookup(InternalRow prefixKey) {
...
+            try {
+                partitionId =
+                        getPartitionId(
+                                prefixKey,
+                                partitionGetter,
+                                tableInfo.getTablePath(),
+                                metadataUpdater);
+            } catch (PartitionNotExistException e) {
+                CompletableFuture<LookupResult> future = new CompletableFuture<>();
+                future.completeExceptionally(e);
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java]: Does it make sense when partition not exist, complete empty result instead of complete exception in this method?

Comment (loserwang1024) [reply fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java]: @luoyuxia I have no idea whether we should do it in flink connector or client. Thus I just do it in flink connector.

Comment (loserwang1024) [reply fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java]: done it

File: fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupResult.java [hunk 2]
```diff
@@ -43,6 +43,11 @@ public LookupResult(List<InternalRow> rowList) {
         this.rowList = rowList;
     }
 
+    public static LookupResult fromSingleRow(@Nullable InternalRow row) {
+        return new LookupResult(
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupResult.java]: nit: just delegate to the constructor method. The logic is same.

File: fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java [hunk 3]
```diff
@@ -150,9 +151,18 @@ public CompletableFuture<LookupResult> lookup(InternalRow prefixKey) {
...
+            try {
+                partitionId =
+                        getPartitionId(
+                                prefixKey,
+                                partitionGetter,
+                                tableInfo.getTablePath(),
+                                metadataUpdater);
+            } catch (PartitionNotExistException e) {
+                CompletableFuture<LookupResult> future = new CompletableFuture<>();
+                future.complete(LookupResult.fromSingleRow(null));
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java]: nit: CompletableFuture.completedFuture(LookupResult.fromSingleRow(null))

File: fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrimaryKeyLookuper.java [hunk 4]
```diff
@@ -107,14 +108,22 @@ public CompletableFuture<LookupResult> lookup(InternalRow lookupKey) {
...
+            try {
+                partitionId =
+                        getPartitionId(
                                 lookupKey,
                                 partitionGetter,
                                 tableInfo.getTablePath(),
                                 metadataUpdater);
+            } catch (PartitionNotExistException e) {
+                CompletableFuture<LookupResult> future = new CompletableFuture<>();
+                future.complete(LookupResult.fromSingleRow(null));
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrimaryKeyLookuper.java]: dito

File: fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupResult.java (hunk 2 above)
Comment (loserwang1024) [reply fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupResult.java]: done it.

**Comment by loserwang1024** [comment]
Modified again, please help review again.

**Review by luoyuxia — APPROVED** [review]
+1

File: fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java [hunk 5]
```diff
@@ -266,6 +269,9 @@ protected void updateMetadata(
             Throwable t = ExceptionUtils.stripExecutionException(e);
             if (t instanceof RetriableException || t instanceof TimeoutException) {
                 LOG.warn("Failed to update metadata, but the exception is re-triable.", t);
+            } else if (t instanceof PartitionNotExistException) {
+                LOG.warn("Failed to update metadata because partition is not exist", t);
```
Comment (polyzos) [inline fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java]: because the partition does not exist

**Comment by polyzos** [comment]
just added one small minor comment.. +1

File: fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java (hunk 5 above)
Comment (loserwang1024) [reply fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java]: Thanks. Just modified it.
