### PR TITLE
[bugfix] TieringService will always fail to generate splits when drop table + create table with same name

### LINKED ISSUE #1191: TieringService will always fail to generate splits when drop table + create table with same name
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

1: start tiering service
2: create a table
3: wait the tiering service have one round of tiering of the table
4: drop the table and create the table with same name table
5: then the tiering service will never tier the new table with same name

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by naivedogger**
### Purpose

Linked issue: close #1191 

### Brief change log
The problem described in the issue is caused by a stale cache which maps tablePath into tableId. This change makes sure that before acquiring the offsets, the cache is always updated.

### Tests
fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/ReCreateSameTableAfterTieringTest.java

### API and Format
No.

### Documentation
No.

### CODE REVIEW

File: fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java [hunk 1]
```diff
@@ -377,12 +377,12 @@ private ListOffsetsResult listOffsets(
             Collection<Integer> buckets,
             OffsetSpec offsetSpec) {
         Long partitionId = null;
-        metadataUpdater.checkAndUpdateTableMetadata(
+        metadataUpdater.updateTableMetadata(
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java]: nit:
you can use ` metadataUpdater.updateTableOrPartitionMetadata(tablePath, null);` instead of introducing a new method.

File: fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java [hunk 2]
```diff
@@ -377,12 +377,12 @@ private ListOffsetsResult listOffsets(
...
                 Collections.singleton(physicalTablePath.getTablePath()));
         long tableId = metadataUpdater.getTableId(physicalTablePath.getTablePath());
         // if partition name is not null, we need to check and update partition metadata
         if (physicalTablePath.getPartitionName() != null) {
-            metadataUpdater.checkAndUpdatePartitionMetadata(physicalTablePath);
+            metadataUpdater.updatePartitionMetadata(physicalTablePath);
```
Comment (luoyuxia) [inline fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java]: nit:
you can use `metadataUpdater.updatePhysicalTableMetadata( Collections.singleton(physicalTablePath))`

File: fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+
+import java.util.Arrays;
+import java.util.Iterator;
+import java.util.List;
+
+import static com.alibaba.fluss.testutils.DataTestUtils.row;
+import static org.assertj.core.api.Assertions.assertThat;
+
+/** A Test case for dropping a pktable after tiering and creating one with the same tablePath. */
+public class DropTableAfterTieringTest extends FlinkPaimonTieringTestBase {
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java]: nit:
```suggestion
class ReCreateSameTableAfterTieringTest extends FlinkPaimonTieringTestBase {
```

File: fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+    protected static void beforeAll() {
+        FlinkPaimonTieringTestBase.beforeAll();
+        execEnv = StreamExecutionEnvironment.getExecutionEnvironment();
+        execEnv.setParallelism(2);
+        execEnv.enableCheckpointing(1000);
+        paimonCatalog = getPaimonCatalog();
+    }
+
+    @Test
+    void testDropTable() throws Exception {
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java]:
```suggestion
    void testReCreateSameTable() throws Exception {
```

File: fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+        // check the status of replica after synced
+        assertReplicaStatus(t2Bucket, 2);
+        // check data in paimon
+        checkDataInPaimonPrimayKeyTable(t1, newRows);
+
+        // stop the tiering job
+        jobClient.cancel().get();
+    }
+
+    private void checkDataInPaimonPrimayKeyTable(
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/DropTableAfterTieringTest.java]: move `checkDataInPaimonPrimayKeyTable` and `getPaimonRowCloseableIterator` to `FlinkPaimonTieringTestBase` so that both it and `PaimonTieringITCase` can share it.

**Review by luoyuxia — APPROVED** [review]
+1
